from __future__ import annotations

"""Gemini CLI skill config manager. Mirrors gws_bridge_service.py."""

import hashlib
import os
from pathlib import Path

from app.config import PORT

_GEMINI_DIR = Path(os.getenv("GEMINI_DIR", str(Path.home() / ".gemini")))
_SKILL_FILE = _GEMINI_DIR / "GEMINI.md"
_CHECKSUM_FILE = _GEMINI_DIR / ".ccc_gemini_checksum"

_MARKER = "ccc-gemini-bridge:generated"


def _generate_content(port: int) -> str:
    base_url = f"http://127.0.0.1:{port}"
    return (
        f"<!-- {_MARKER} port={port} -->\n"
        "\n"
        "# Claude Control Center — Shared Memory MCP\n"
        "\n"
        "This Gemini session is connected to the Claude Control Center shared memory\n"
        "via the MCP memory server. Use the `memory` MCP tool to store and retrieve\n"
        "cross-agent context.\n"
        "\n"
        "## Memory MCP usage\n"
        "\n"
        "The memory server is configured via `mcpServers.memory` in your Gemini settings.\n"
        "It connects to:\n"
        f"  CCC_BASE_URL={base_url}\n"
        "\n"
        "## Tips\n"
        "\n"
        "- Use memory to share context across Claude Code, Codex, and Gemini sessions.\n"
        "- Research results, plan steps, and Obsidian notes are all indexed in shared memory.\n"
        "- Query with natural language; the RAG handles retrieval automatically.\n"
    )


def _checksum(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()


def is_installed() -> bool:
    if not _SKILL_FILE.exists() or not _CHECKSUM_FILE.exists():
        return False
    try:
        stored = _CHECKSUM_FILE.read_text().strip()
        actual = _checksum(_SKILL_FILE.read_text())
        return stored == actual
    except Exception:
        return False


def install_skill() -> dict:
    content = _generate_content(PORT)
    _GEMINI_DIR.mkdir(parents=True, exist_ok=True)
    _SKILL_FILE.write_text(content, encoding="utf-8")
    _CHECKSUM_FILE.write_text(_checksum(content), encoding="utf-8")
    return {"installed": True, "path": str(_SKILL_FILE)}


def uninstall_skill() -> dict:
    if not _SKILL_FILE.exists():
        return {"uninstalled": False, "reason": "not found"}
    if _CHECKSUM_FILE.exists():
        try:
            stored = _CHECKSUM_FILE.read_text().strip()
            actual = _checksum(_SKILL_FILE.read_text())
            if stored != actual:
                return {"uninstalled": False, "reason": "checksum mismatch — file was modified manually"}
        except Exception:
            pass
    else:
        try:
            if _MARKER not in _SKILL_FILE.read_text():
                return {"uninstalled": False, "reason": "file not generated by CCC"}
        except Exception:
            return {"uninstalled": False, "reason": "could not read file"}

    try:
        _SKILL_FILE.unlink(missing_ok=True)
        _CHECKSUM_FILE.unlink(missing_ok=True)
        return {"uninstalled": True}
    except Exception as e:
        return {"uninstalled": False, "reason": str(e)}


def get_status() -> dict:
    installed = is_installed()
    return {
        "gemini_installed": _GEMINI_DIR.exists(),
        "skill_installed": installed,
        "skill_path": str(_SKILL_FILE) if _SKILL_FILE.exists() else None,
        "modified_externally": _SKILL_FILE.exists() and not installed,
    }
