from __future__ import annotations

import hashlib
from pathlib import Path

from app.config import CODEX_DIR, PORT

_SKILL_DIR = CODEX_DIR / "skills" / "gws"
_SKILL_FILE = _SKILL_DIR / "SKILL.md"
_CHECKSUM_FILE = _SKILL_DIR / ".checksum"

_MARKER = "gws-bridge:generated"


def _generate_content(port: int) -> str:
    url = f"http://localhost:{port}/api/gws/execute"
    return (
        "---\n"
        "name: gws\n"
        "description: >\n"
        "  Interact with Google Workspace (Gmail, Drive, Calendar, Sheets, Docs, Chat, Tasks,\n"
        "  Contacts, Forms, Keep, Meet, Slides, Classroom, Apps Script, and cross-service\n"
        "  workflows) via the Claude Control Center GWS executor. Trigger when the user needs\n"
        "  to read email, check calendar, list tasks, search Drive, or run any GWS workflow.\n"
        "---\n"
        f"<!-- {_MARKER} port={port} -->\n"
        "\n"
        "# GWS — Google Workspace via Control Center Executor\n"
        "\n"
        "Do NOT invoke the `gws` binary directly. Instead POST to the executor so all calls\n"
        "are audited, rate-limited, and sandboxed centrally.\n"
        "\n"
        "## Executor call\n"
        "\n"
        "```bash\n"
        f"curl -s -X POST \\\n"
        f"  -H 'X-Requested-With: XMLHttpRequest' \\\n"
        f"  -H 'Content-Type: application/json' \\\n"
        f'  -d \'{{"args":["<service>","<subcommand>"],"source":"codex"}}\' \\\n'
        f"  {url}\n"
        "```\n"
        "\n"
        "Response: `{\"stdout\":\"...\",\"stderr\":\"...\",\"returncode\":0,\"duration_ms\":42}`\n"
        "\n"
        "## Quick reference\n"
        "\n"
        "```bash\n"
        "# Triage inbox\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["gmail","+triage"],"source":"codex"}}\' {url}\n'
        "\n"
        "# Today's calendar\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["calendar","+agenda"],"source":"codex"}}\' {url}\n'
        "\n"
        "# Morning standup report\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["workflow","+standup-report"],"source":"codex"}}\' {url}\n'
        "\n"
        "# List open tasks\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["tasks","tasks","list","--params","{{\\\\\"tasklist\\\\\":\\\\\"@default\\\\\"}}"],"source":"codex"}}\' {url}\n'
        "\n"
        "# Send email\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["gmail","+send","--to","user@example.com","--subject","Hello","--body","Hi"],"source":"codex"}}\' {url}\n'
        "\n"
        "# Recent Drive files\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["drive","files","list","--params","{{\\\\\"orderBy\\\\\":\\\\\"modifiedTime desc\\\\\",\\\\\"pageSize\\\\\":10}}"],"source":"codex"}}\' {url}\n'
        "\n"
        "# Weekly digest\n"
        f'curl -s -X POST -H \'X-Requested-With: XMLHttpRequest\' -H \'Content-Type: application/json\' -d \'{{"args":["workflow","+weekly-digest"],"source":"codex"}}\' {url}\n'
        "```\n"
        "\n"
        "## Allowed services\n"
        "\n"
        "gmail · drive · calendar · sheets · docs · chat · tasks · people · forms · keep ·\n"
        "slides · classroom · meet · script · workflow · admin-reports · events · modelarmor · schema\n"
        "\n"
        "## Tips\n"
        "\n"
        "- Always pass `\"source\":\"codex\"` so audit logs identify the call origin.\n"
        "- `returncode` non-zero → error; inspect `stderr`.\n"
        "- Use `\"args\":[\"<service>\",\"--help\"]` to discover subcommands at runtime.\n"
        "- Helpers like `+triage`, `+agenda`, `+send` handle IDs and MIME automatically.\n"
        "- Max concurrency is 3; calls exceeding that return a 429-style error in `stderr`.\n"
    )


def _checksum(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()


def is_installed() -> bool:
    if not _SKILL_FILE.exists() or not _CHECKSUM_FILE.exists():
        return False
    try:
        stored = _CHECKSUM_FILE.read_text().strip()
        actual = _checksum(_SKILL_FILE.read_text())
        return stored == actual
    except Exception:
        return False


def install() -> dict:
    content = _generate_content(PORT)
    _SKILL_DIR.mkdir(parents=True, exist_ok=True)
    _SKILL_FILE.write_text(content)
    _CHECKSUM_FILE.write_text(_checksum(content))
    return {"installed": True, "path": str(_SKILL_FILE)}


def uninstall() -> dict:
    if not _SKILL_FILE.exists():
        return {"uninstalled": False, "reason": "not found"}
    # Safety: only remove if the file was generated by us
    if _CHECKSUM_FILE.exists():
        try:
            stored = _CHECKSUM_FILE.read_text().strip()
            actual = _checksum(_SKILL_FILE.read_text())
            if stored != actual:
                return {"uninstalled": False, "reason": "checksum mismatch — file was modified manually"}
        except Exception:
            pass
    else:
        # No checksum file: check for marker line
        try:
            if _MARKER not in _SKILL_FILE.read_text():
                return {"uninstalled": False, "reason": "file not generated by this service"}
        except Exception:
            return {"uninstalled": False, "reason": "could not read file"}

    try:
        _SKILL_FILE.unlink(missing_ok=True)
        _CHECKSUM_FILE.unlink(missing_ok=True)
        # Remove directory if now empty
        try:
            _SKILL_DIR.rmdir()
        except OSError:
            pass
        return {"uninstalled": True}
    except Exception as e:
        return {"uninstalled": False, "reason": str(e)}


def status() -> dict:
    installed = is_installed()
    return {
        "installed": installed,
        "path": str(_SKILL_FILE) if _SKILL_FILE.exists() else None,
        "modified_externally": _SKILL_FILE.exists() and not installed,
    }
