type QueryKeyPart = string | number | boolean | null | undefined;

const key = (...parts: QueryKeyPart[]) => {
  let length = parts.length;
  while (length > 1 && parts[length - 1] === undefined) {
    length -= 1;
  }
  return parts.slice(0, length);
};

export const queryKeys = {
  activeSessions: () => key('active-sessions'),
  advisorStats: () => key('advisor-stats'),
  advisorUsages: (page?: number) => key('advisor-usages', page),
  agent: (id?: string | null) => key('agent', id),
  agentEnvironments: () => key('agent-environments'),
  agentLibrary: () => key('agent-library'),
  agentViewAgents: () => key('agent-view-agents'),
  agentMemory: (agentId?: string | null) => key('agent-memory', agentId),
  agentPreview: (agentId?: string | null) => key('agent-preview', agentId),
  agentSession: (sessionId?: string) => key('agent-session', sessionId),
  agentSessions: (agentId?: string) => key('agent-sessions', agentId),
  agentStatus: () => key('agent-status'),
  agents: () => key('agents'),
  analyticsStats: (days?: string | number) => key('analytics-stats', days),
  semanticCatalog: () => key('semantic-catalog'),
  semanticQuery: (metric?: string, groupBy?: string | null, days?: string | number, filters?: string) =>
    key('semantic-query', metric, groupBy ?? undefined, days, filters),
  changelogReleases: () => key('changelog-releases'),
  changelogWhatsNew: () => key('changelog-whats-new'),
  claudeMdContent: (selectedId?: string | null) => key('claude-md-content', selectedId),
  claudeMdFiles: () => key('claude-md-files'),
  claudeMemories: () => key('claude-memories'),
  codeburnStats: (days?: string | number) => key('codeburn-stats', days),
  codexCliAnalytics: (days?: string | number) => key('codex-cli-analytics', days),
  codexCliAuth: () => key('codex-cli-auth'),
  codexCliConfig: () => key('codex-cli-config'),
  codexCliHistory: (page?: number, search?: string) => key('codex-cli-history', page, search),
  codexCliModels: () => key('codex-cli-models'),
  codexCliSession: (sessionId?: string) => key('codex-cli-session', sessionId),
  codexCliSessionIndex: (page?: number) => key('codex-cli-session-index', page),
  codexCliSessionStats: () => key('codex-cli-session-stats'),
  codexCliSessions: (
    page?: number,
    search?: string,
    projectFilter?: string,
    modelFilter?: string,
    sort?: string,
    starredOnly?: boolean,
    includeArchived?: boolean,
    minTools?: number | null
  ) =>
    key(
      'codex-cli-sessions',
      page,
      search,
      projectFilter,
      modelFilter,
      sort,
      starredOnly,
      includeArchived,
      minTools
    ),
  codexCliSkill: (skillId?: string | null) => key('codex-cli-skill', skillId),
  codexCliSkills: () => key('codex-cli-skills'),
  codexCliSystemSkills: () => key('codex-cli-system-skills'),
  codexCliVersion: () => key('codex-cli-version'),
  codexHooks: () => key('codex-hooks'),
  codexStats: () => key('codex-stats'),
  codexUsages: (page?: number) => key('codex-usages', page),
  commands: () => key('commands'),
  dashboardFleet: () => key('dashboard-fleet'),
  dockerStacks: () => key('docker-stacks'),
  dockerDetail: (name?: string) => key('docker-detail', name),
  dockerLogs: (name?: string, lines?: number) => key('docker-logs', name, lines),
  geminiAnalytics: (days?: string | number) => key('gemini-analytics', days),
  geminiMd: () => key('gemini-md'),
  geminiMemory: (page?: number, search?: string) => key('gemini-memory', page, search),
  geminiSession: (sessionId?: string) => key('gemini-session', sessionId),
  geminiSessionStats: () => key('gemini-session-stats'),
  geminiSessions: (
    page?: number,
    search?: string,
    projectFilter?: string,
    modelFilter?: string,
    sort?: string,
    starredOnly?: boolean,
    includeArchived?: boolean,
    minTools?: number | null
  ) =>
    key(
      'gemini-sessions',
      page,
      search,
      projectFilter,
      modelFilter,
      sort,
      starredOnly,
      includeArchived,
      minTools
    ),
  geminiSettings: () => key('gemini-settings'),
  geminiSkill: (skillId?: string | null) => key('gemini-skill', skillId),
  geminiSkills: () => key('gemini-skills'),
  gitRepos: () => key('git-repos'),
  gitGraph: (repoId?: string, limit?: number) => key('git-graph', repoId, limit),
  gitWorktrees: (repoId?: string) => key('git-worktrees', repoId),
  gitAllWorktrees: () => key('git-all-worktrees'),
  githubActivity: (days?: number) => key('github-activity', days),
  githubBranches: (repoPath?: string | null) => key('github-branches', repoPath),
  githubIssues: () => key('github-issues'),
  githubMilestones: () => key('github-milestones'),
  githubPrs: () => key('github-prs'),
  githubRepos: () => key('github-repos'),
  githubRoots: () => key('github-roots'),
  githubStatus: () => key('github-status'),
  gatewayModels: () => key('gateway-models'),
  gwsActivity: (sourceFilter?: string, serviceFilter?: string, page?: number) =>
    key('gws-activity', sourceFilter, serviceFilter, page),
  gwsAudit: () => key('gws-audit'),
  gwsBridge: () => key('gws-bridge'),
  gwsRecipes: () => key('gws-recipes'),
  gwsSnapshot: () => key('gws-snapshot'),
  gwsStatus: () => key('gws-status'),
  healthReferences: () => key('health-references'),
  invoicingConfig: () => key('invoicing-config'),
  invoicingTabs: (spreadsheet?: string) => key('invoicing-tabs', spreadsheet),
  invoicePreview: (spreadsheet?: string, tab?: string) => key('invoice-preview', spreadsheet, tab),
  crmConfig: () => key('crm-config'),
  crmClients: () => key('crm-clients'),
  crmDeals: () => key('crm-deals'),
  crmPipeline: () => key('crm-pipeline'),
  history: (offset?: number) => key('history', offset),
  hooks: (scope?: string) => key('hooks', scope),
  insights: () => key('insights'),
  mcpBridgeStatus: () => key('mcp-bridge-status'),
  newsFeed: () => key('news-feed'),
  newsIdeas: () => key('news-ideas'),
  newsSources: () => key('news-sources'),
  mcpServers: (scope?: string) => key('mcp-servers', scope),
  memory: (projectId?: string) => key('memory', projectId),
  memoryFile: (projectId?: string, filename?: string | null) => key('memory-file', projectId, filename),
  messages: (projectId?: string, sessionId?: string) => key('messages', projectId, sessionId),
  search: (q?: string) => key('search', q),
  obsidianNote: (vaultId?: string, selectedNote?: string | null) =>
    key('obsidian-note', vaultId, selectedNote),
  obsidianNotes: (vaultId?: string) => key('obsidian-notes', vaultId),
  obsidianSearch: (vaultId?: string, search?: string) => key('obsidian-search', vaultId, search),
  obsidianSyncStatus: (vaultId?: string) => key('obsidian-sync-status', vaultId),
  obsidianVaults: () => key('obsidian-vaults'),
  plan: (slug?: string) => key('plan', slug),
  planProgress: (slug?: string) => key('plan-progress', slug),
  plans: () => key('plans'),
  plugins: () => key('plugins'),
  projects: () => key('projects'),
  ragStatus: () => key('rag-status'),
  ragIngestStatus: () => key('rag-ingest-status'),
  ragIngestLog: () => key('rag-ingest-log'),
  ragLiveDocs: (page?: number) => key('rag-live-docs', page),
  researchJobLog: (jobId?: string) => key('research-job-log', jobId),
  researchJobs: () => key('research-jobs'),
  researchSourceStatus: () => key('research-source-status'),
  videoResearchJobs: () => key('video-research-jobs'),
  videoResearchJob: (jobId?: string) => key('video-research-job', jobId),
  videoResearchDeliverable: (jobId?: string, name?: string) =>
    key('video-research-deliverable', jobId, name),
  videoResearchSourceStatus: () => key('video-research-source-status'),
  routineStats: () => key('routine-stats'),
  routineUsages: (page?: number) => key('routine-usages', page),
  loops: () => key('loops'),
  loop: (id?: string) => key('loop', id),
  loopRuns: (id?: string) => key('loop-runs', id),
  loopStats: (id?: string) => key('loop-stats', id),
  loopCron: (id?: string) => key('loop-cron', id),
  loopDiscovered: () => key('loop-discovered'),
  schedulerStatus: () => key('scheduler-status'),
  schedulerActions: () => key('scheduler-actions'),
  schedulerTasks: () => key('scheduler-tasks'),
  schedulerRuns: (taskId?: string) => key('scheduler-runs', taskId),
  rules: () => key('rules'),
  sessions: (projectId?: string) => key('sessions', projectId),
  settings: () => key('settings'),
  skills: () => key('skills'),
  subagent: (projectId?: string, sessionId?: string, agentId?: string | null) =>
    key('subagent', projectId, sessionId, agentId),
  tasks: () => key('tasks'),
  goals: () => key('goals'),
  sessionGoals: (projectId?: string, sessionId?: string) => key('goals', projectId, sessionId),
  evalSessions: (days?: number | string, tool?: string, grade?: string, page?: number) =>
    key('eval-sessions', days, tool, grade, page),
  evalSession: (sessionId?: string) => key('eval-session', sessionId),
  evalStats: (days?: number | string) => key('eval-stats', days),
  evalBudget: () => key('eval-budget'),
  cacheStats: (days?: string | number) => key('cache-stats', days),
  sessionCacheStats: (projectDir?: string, sessionId?: string) =>
    key('session-cache-stats', projectDir, sessionId),
} as const;
